### ISSUE TITLE
[FB] 画面下部の情報量が多い気がする

### ISSUE THREAD

**Issue by Colk-tech** [loxygenK/musical_typer#26]
これは好みの問題な気がする...
のであんまり参考にならないフィードバック()

**Comment by loxygenK** [comment]
確かに正確率は3つもいらないナ
`fewer-detail-info`ブランチで操作します

**Comment by loxygenK** [comment]
![image](https://user-images.githubusercontent.com/55672846/74604368-ad71fd00-5100-11ea-85d4-8202f622e081.png)
こうなりました
多分あなたABCで忙しいのでmergeしないで放置しておきますね…

**Comment by Colk-tech** [comment]
かえってきました！！！！
ええやん！！！
みやすい

**Comment by loxygenK** [comment]
アイシテル
じゃあこれでmergeしちゃうゾ

**Comment by loxygenK** [comment]
できた！close！ズドン！
