### ISSUE TITLE
spaceキーについて

### ISSUE THREAD

**Issue by Yorime** [loxygenK/musical_typer#35]
spaceキーを押したときに歌詞が出るのは長押しだとnoobの俺はきついので個人的に歌詞が先のぶんまであるとうれしい！

**Comment by loxygenK** [comment]
Shiftボタンで固定ができるという分かりづらい仕様を採用しているゾ
READMEに書かなきゃ()

**Comment by loxygenK** [comment]
READMEに追加をするので `rdme-next_lyrics` ブランチで操作をします

**Comment by Yorime** [comment]
もうあったのか天才好き

**Comment by loxygenK** [comment]
天才ですまんと言いたいんだがわかりづらいのでこれは天才ではないですね…

**Comment by loxygenK** [comment]
#36 で対応完了！Close(解決としてマーク) します！
