### ISSUE TITLE
Linuxでキー操作に反応しない

### ISSUE THREAD

**Issue by kawaemon** [loxygenK/musical_typer#38]
突然のIssue失礼します...

ArchLinux 5.5.2-zen1-1-zen 上で、キー操作を受け付けません。
原因としては、イベントループ内の `Romautil.is_readable_key_pressed`関数内の
`if pygame.key.get_mods(): return False`式に常に引っかかっているようです...

`print (event)`で得られた情報を載せておきます。
`<Event(2-KeyDown {'unicode': 'r', 'key': 114, 'mod': 4096, 'scancode': 27, 'window': None})>`

**Comment by loxygenK** [comment]
報告ありがとうございます！
Ctrlキーなどの修飾キーを弾くためのコードがバグを発生させたようです…

forkされているようなのでPRを見てmergeします。ご協力ありがとうございます！

**Comment by loxygenK** [comment]
#39 をmergeしたのでcloseします。ありがとうございました！
