### ISSUE TITLE
「じゃ」をjaで打つと歌詞の位置がずれる

### ISSUE THREAD

**Issue by kawaemon** [loxygenK/musical_typer#41]
zyaをjaで打つと、zyaがjiaに変化し「じゃ」から「ね」に表示位置がずれます
画像参照

![image](https://user-images.githubusercontent.com/34652535/74605630-25462480-510d-11ea-88f4-db23dafcf2c9.png)

**Comment by loxygenK** [comment]
ご報告ありがとうございます！
家のルールで10:30以降はPCが使えなくなってしまうので、明日対処を行うつもりです。

**Comment by loxygenK** [comment]
おはようございます！`lyrics-ja-fix`ブランチで操作します。

**Comment by loxygenK** [comment]
#48 で対応完了しました！Closeします。
