### ISSUE TITLE
コマンドライン引数未指定、もしくはファイルが存在しない場合の挙動について

### ISSUE THREAD

**Issue by nanigasi-san** [loxygenK/musical_typer#46]
めんどくさいオタクなので気になってしまったんですけど、ここはstderrにエラーを吐いてプログラムを終了しているわけで、例外を吐かせるのが自然に感じたんですが何か理由があってですか？

![image](https://user-images.githubusercontent.com/44631106/74607365-d358cb00-511b-11ea-9479-8dfdb151483f.png)

https://github.com/loxygenK/musical_typer/blob/d3d3983d25b7850ac4901a5dc9b9cef41b1fb918/Main.py#L33

**Comment by loxygenK** [comment]
例外が自然だったのですね…ありがとうございます！
`cmd_arg_err` ブランチで操作します。

**Comment by loxygenK** [comment]
ところで理由はあまりなくて、ユーザーの入力に対し例外をスローすることに馴染みがなかったのでstderrにエラーメッセージを出力する方法を取りました。

**Comment by loxygenK** [comment]
#47 のPRで対応しました！closeしてしまいます。

**Comment by nanigasi-san** [comment]
なるほど！エラーを出力して終了だと、｢どこで終わったか、ミスしたか｣が分からないので基本的には例外を投げることが多いかなと思います(Pythonなら例外自作も楽ですし)

クソしょうもないissueに対応して頂いてありがたい！

**Comment by loxygenK** [comment]
おお・・・とてもためになりました、ありがとうございます！
