### ISSUE TITLE
リトライ機能

### ISSUE THREAD

**Issue by kawaemon** [loxygenK/musical_typer#54]
リザルト画面でリトライできるような仕組みがあるといいと思います。。。
現状だと再起動する手間があるので。

**Comment by loxygenK** [comment]
`retry`ブランチで操作します。ありがとうございます！

**Comment by loxygenK** [comment]
#55 のPRで対応したのでcloseします。ただデザインがあまりにも…
もしデザインのアイディアがあれば共有してほしいです…！
